spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/librarydb
        username: postgres
        password: root
        driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update
    server:
      port: 8080

    google:
      books:
        api-key: "AIzaSyCwdR--XNf10VGYgMf2TEXFjscsNzHc9bE"
